fragment HomePage on HomePage {
  __typename
  MetaTitle
  MainBody
  MainContentArea {
    ...ExpandedContentAreaItem
  }
  BottomContentArea {
    ...ExpandedContentAreaItem
  }
  HideSiteHeader
  Url
}
