fragment ExpandedContentAreaItem on ContentAreaItemModelSearch {
  ContentLink {
    GuidValue
    Id
    __typename
    Expanded {
      ContentType
      __typename
      Name
      ...ContainerBlock
      ...AllChildBlocks
    }
  }
}
